# Generated by Django 4.2.1 on 2023-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0003_alter_recipe_cooking_time_alter_tag_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="images/recipes/"),
        ),
    ]
