# Generated by Django 3.2.9 on 2023-06-04 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0006_shoppingcart_favorite_unique_favorite_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="quantity",
            new_name="amount",
        ),
    ]
